// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/base.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - CookIt</title><script src=\"https://cdn.tailwindcss.com\"></script><style>\r\n\t\t\t\t@keyframes fadeIn {\r\n\t\t\t\t\tfrom { opacity: 0; transform: translateY(20px); }\r\n\t\t\t\t\tto { opacity: 1; transform: translateY(0); }\r\n\t\t\t\t}\r\n\t\t\t\t.fade-in {\r\n\t\t\t\t\tanimation: fadeIn 0.6s ease-out;\r\n\t\t\t\t}\r\n\t\t\t</style></head><body class=\"bg-gradient-to-br from-orange-50 via-amber-50 to-yellow-50 min-h-screen\"><nav class=\"bg-white shadow-lg border-b border-orange-200\"><div class=\"container mx-auto px-6 py-4\"><div class=\"flex items-center justify-between\"><div class=\"flex items-center space-x-2\"><span class=\"text-3xl\">🍳</span> <span class=\"text-2xl font-bold text-orange-600\">CookIt</span></div><div class=\"flex items-center space-x-6\"><a href=\"/\" class=\"text-gray-700 hover:text-orange-600 transition\">Home</a> <a href=\"/recipes\" class=\"text-gray-700 hover:text-orange-600 transition\">Recipes</a><div id=\"auth-links\"><a href=\"/login\" class=\"text-gray-700 hover:text-orange-600 transition\" id=\"login-link\">Login</a> <a href=\"/register\" class=\"text-gray-700 hover:text-orange-600 transition ml-4\" id=\"register-link\">Register</a> <button onclick=\"logout()\" class=\"hidden text-gray-700 hover:text-orange-600 transition ml-4\" id=\"logout-btn\">Logout</button></div></div></div></div></nav><main class=\"container mx-auto px-6 py-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main><footer class=\"bg-white border-t border-orange-200 mt-20\"><div class=\"container mx-auto px-6 py-8 text-center text-gray-600\"><p>© 2024 CookIt. Made with ❤️ and Go</p></div></footer><script src=\"/static/js/app.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
