// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Register() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-md mx-auto fade-in\"><div class=\"bg-white rounded-2xl shadow-2xl p-8 border-t-4 border-orange-500\"><div class=\"text-center mb-8\"><div class=\"text-6xl mb-4\">👨\u200d🍳</div><h2 class=\"text-3xl font-bold text-gray-800\">Join CookIt</h2><p class=\"text-gray-600 mt-2\">Start your culinary journey today</p></div><form id=\"register-form\" class=\"space-y-6\"><div><label class=\"block text-gray-700 font-semibold mb-2\" for=\"reg-username\">Username</label> <input type=\"text\" id=\"reg-username\" name=\"username\" required class=\"w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange-500 focus:ring-2 focus:ring-orange-200 outline-none transition\" placeholder=\"Choose a username\"></div><div><label class=\"block text-gray-700 font-semibold mb-2\" for=\"reg-password\">Password</label> <input type=\"password\" id=\"reg-password\" name=\"password\" required minlength=\"6\" class=\"w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange-500 focus:ring-2 focus:ring-orange-200 outline-none transition\" placeholder=\"Create a strong password\"><p class=\"text-sm text-gray-500 mt-1\">Minimum 6 characters</p></div><div id=\"reg-error-message\" class=\"hidden bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded\"></div><div id=\"reg-success-message\" class=\"hidden bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded\"></div><button type=\"submit\" class=\"w-full bg-orange-600 hover:bg-orange-700 text-white font-bold py-3 rounded-lg transition shadow-lg hover:shadow-xl\">Create Account</button></form><p class=\"text-center text-gray-600 mt-6\">Already have an account?  <a href=\"/login\" class=\"text-orange-600 font-semibold hover:underline\">Login here</a></p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Register").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
